### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "Contact Us Page",
  "date": "2021-02-02T12:00:00Z",
  "description": "Create a Contact Us Page",
  "priority": "high",
  "status": "inProgress"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
  "id": "8069391e-d027-11ed-afa1-0242ac120002",
  "status": "inProgress"
}